### ISSUE TITLE
Depends on bcrypt, but it's not listed in requirements.txt

### ISSUE THREAD

**Issue by fwaggle** [cwinfosec/epic_shell#3]
As title said, requirements.txt is incomplete as it does not list bcrypt, which the script depends on. Hope that helps!

**Comment by cwinfosec** [comment]
> As title said, requirements.txt is incomplete as it does not list bcrypt, which the script depends on. Hope that helps!

Thank you for the heads-up! I have added the bcrypt version to requirements.txt.
